version: '3.4'

services:
  serviceoneserverapi:
      image: ${DOCKER_REGISTRY-}serviceoneserverapi
      stdin_open: true
      tty: true
      build:
        context: .
        dockerfile: ServiceOneServerApi/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_HTTPS_PORT=5001
        # Export HTTPS dev certificate as pfx with your own password (directory should match volume below)
        #    dotnet dev-certs https -ep ${APPDATA}/ASP.NET/Https/aspnetapp.pfx -p mypassword
        - ASPNETCORE_Kestrel__Certificates__Default__Password=teste
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/aspnetapp.pfx
      ports:
        - "5000:80"
        - "5001:443"
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${HOME}/.aspnet/https:/https/:ro
