version: '3.4'

services:
  serviceoneserverapi:
      image: ${DOCKER_REGISTRY-}serviceoneserverapi
      build:
        context: .
        dockerfile: ServiceOneServerApi/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+;http://+
        - ASPNETCORE_HTTPS_PORT=5001
        # Export HTTPS dev certificate as pfx with your own password (directory should match volume below)
        #    dotnet dev-certs https -ep ${APPDATA}/ASP.NET/Https/aspnetapp.pfx -p mypassword
      ports:
        - "5000:80"
        - "5001:443"

  serviceoneclientconsole:
    image: ${DOCKER_REGISTRY-}serviceoneclientconsole
    build:
      context: .
      dockerfile: ServiceOneClientConsole/Dockerfile

  servicetwoclient:
    image: ${DOCKER_REGISTRY-}servicetwoclient
    ports: 
      - 5555:5555
    build:
      context: .
      dockerfile: ServiceTwoClient/Dockerfile 

  servicetwoserver:
    image: ${DOCKER_REGISTRY-}servicetwoserver
    ports: 
      - 50056:50056
    build:
      context: .
      dockerfile: ServiceTwoServer/Dockerfile