FROM ubuntu:latest
EXPOSE 50056

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev unixodbc-dev && \
    apt-get install -y curl

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN curl https://packages.microsoft.com/config/ubuntu/19.04/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN apt-get update -y

RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17

RUN mkdir /usr/src/app

WORKDIR /usr/src/app

ADD . /usr/src/app

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

ENV PYTHONUNBUFFERED 1

ENTRYPOINT [ "python3" ]

CMD [ "ServiceTwoServer.py" ]