FROM ubuntu:latest
EXPOSE 5555

RUN apt-get update -y && \
    apt-get install -y python3 python3-pip python3-dev unixodbc-dev

RUN mkdir /usr/src/app

WORKDIR /usr/src/app

ADD . /usr/src/app

COPY ./requirements.txt .
COPY ./runserver.py /usr/src/app

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

COPY . .

ENTRYPOINT [ "python3" ]

CMD [ "runserver.py" ]