# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serviceTwo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='serviceTwo.proto',
  package='STwo',
  syntax='proto3',
  serialized_options=_b('\n\016io.grpc.a.stwoB\004stwoP\001\242\002\004SWTO'),
  serialized_pb=_b('\n\x10serviceTwo.proto\x12\x04STwo\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1a\n\nByeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1b\n\x08\x42yeReply\x12\x0f\n\x07message\x18\x01 \x01(\t2k\n\nServiceTwo\x12/\n\x05Teste\x12\x12.STwo.HelloRequest\x1a\x10.STwo.HelloReply\"\x00\x12,\n\x06SayBye\x12\x10.STwo.ByeRequest\x1a\x0e.STwo.ByeReply\"\x00\x42\x1f\n\x0eio.grpc.a.stwoB\x04stwoP\x01\xa2\x02\x04SWTOb\x06proto3')
)




_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='STwo.HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='STwo.HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=54,
)


_HELLOREPLY = _descriptor.Descriptor(
  name='HelloReply',
  full_name='STwo.HelloReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='STwo.HelloReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=85,
)


_BYEREQUEST = _descriptor.Descriptor(
  name='ByeRequest',
  full_name='STwo.ByeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='STwo.ByeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=113,
)


_BYEREPLY = _descriptor.Descriptor(
  name='ByeReply',
  full_name='STwo.ByeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='STwo.ByeReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HelloReply'] = _HELLOREPLY
DESCRIPTOR.message_types_by_name['ByeRequest'] = _BYEREQUEST
DESCRIPTOR.message_types_by_name['ByeReply'] = _BYEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'serviceTwo_pb2'
  # @@protoc_insertion_point(class_scope:STwo.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'serviceTwo_pb2'
  # @@protoc_insertion_point(class_scope:STwo.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

ByeRequest = _reflection.GeneratedProtocolMessageType('ByeRequest', (_message.Message,), {
  'DESCRIPTOR' : _BYEREQUEST,
  '__module__' : 'serviceTwo_pb2'
  # @@protoc_insertion_point(class_scope:STwo.ByeRequest)
  })
_sym_db.RegisterMessage(ByeRequest)

ByeReply = _reflection.GeneratedProtocolMessageType('ByeReply', (_message.Message,), {
  'DESCRIPTOR' : _BYEREPLY,
  '__module__' : 'serviceTwo_pb2'
  # @@protoc_insertion_point(class_scope:STwo.ByeReply)
  })
_sym_db.RegisterMessage(ByeReply)


DESCRIPTOR._options = None

_SERVICETWO = _descriptor.ServiceDescriptor(
  name='ServiceTwo',
  full_name='STwo.ServiceTwo',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=144,
  serialized_end=251,
  methods=[
  _descriptor.MethodDescriptor(
    name='Teste',
    full_name='STwo.ServiceTwo.Teste',
    index=0,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HELLOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SayBye',
    full_name='STwo.ServiceTwo.SayBye',
    index=1,
    containing_service=None,
    input_type=_BYEREQUEST,
    output_type=_BYEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICETWO)

DESCRIPTOR.services_by_name['ServiceTwo'] = _SERVICETWO

# @@protoc_insertion_point(module_scope)
